background_learning:
  default_settings:
    learning_rate: 0.01
    stability_threshold: 0.85
    min_object_persistence: 30
    abandoned_object_timeout: 300
    background_update_interval: 100
    enable_adaptive_learning: true
  
  cameras:
    default:
      learning_rate: 0.01
      abandoned_object_timeout: 300
      detection_zones:
        - name: "full_frame"
          polygon: [[0, 0], [1280, 0], [1280, 720], [0, 720]]
          importance: 1.0
          expected_objects: []

alerts:
  email:
    enabled: false
    # Configure when ready
  
  webhook:
    enabled: false
    # Configure when ready
